spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect

  jackson:
    default-property-inclusion: non_null

  # https://stackoverflow.com/questions/40241843/failed-to-start-bean-documentationpluginsbootstrapper-in-spring-data-rest
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    favicon:
      enabled: false
